### ISSUE TITLE
Object #<Client> has no method 'destroy'

### ISSUE THREAD

**Issue by cedriclombardot** [benschmaus/nodeload#15]
Hi,

When i run the quick start sample https://github.com/benschmaus/nodeload/blob/master/doc/nodeload.md, i have the next error : 

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Client> has no method 'destroy'
    at /var/local/webroot/bookmarks-node/node_modules/nodeload/nodeload.js:9:506
    at Client.<anonymous> (/var/local/webroot/bookmarks-node/node_modules/nodeload/nodeload.js:10:180)
    at Client.emit (events.js:88:20)
    at ClientRequest.<anonymous> (http.js:1511:10)
    at ClientRequest.emit (events.js:67:17)
    at Socket.<anonymous> (http.js:1114:11)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:301:25)
    at EventEmitter._tickCallback (node.js:192:40)
```

I use node v0.6.5

Thanks in advance

**Comment by nponeccop** [comment]
+1. The bug still happens with node v0.6.12

**Comment by sarenji** [comment]
+1. Node v0.6.14 has the same problem.

**Comment by thegoleffect** [comment]
The pull request 16, https://github.com/benschmaus/nodeload/pull/16, has a fix for this issue.

**Comment by shelleyp** [comment]
Question: is this module still supported by the original author? I need to know before I include mention in my book.
